tclap: TCLAP::Arg Class Reference
TCLAP::Arg Class Reference abstract
A virtual base class that defines the essential data for all arguments.
#include <Arg.h>
Public Member Functions
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool processArg (int *i, std::vector< std::string > &args)=0
Pure virtual method meant to handle the parsing and value assignment of the string on the command line.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual std::string shortID (const std::string &valueId="val") const
Returns a short ID for the usage.
virtual std::string longID (const std::string &valueId="val") const
Returns a long ID for the usage.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
virtual bool hasLabel () const
Static Public Member Functions
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Protected Member Functions
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Detailed Description
A virtual base class that defines the essential data for all arguments.
This class, or one of its existing children, must be subclassed to do anything.
Definition at line 53 of file Arg.h.
Constructor & Destructor Documentation
Arg()
TCLAP::Arg::Arg (const std::string & flag, const std::string & name, const std::string & desc, bool req, bool valreq, Visitor * v = NULL) inline protected
Primary constructor.
YOU (yes you) should NEVER construct an Arg directly, this is a base class that is extended by various children that are meant to be used. Use SwitchArg, ValueArg, MultiArg, UnlabeledValueArg, or UnlabeledMultiArg instead.
Parameters
flag - The flag identifying the argument.
name - The name identifying the argument.
desc - The description of the argument, used in the usage.
req - Whether the argument is required.
valreq - Whether the a value is required for the argument.
v - The visitor checked by the argument. Defaults to NULL.
Definition at line 446 of file Arg.h.
References _acceptsMultipleValues, _alreadySet, _description, _flag, _ignoreable, _name, _required, _requireLabel, _setBy, _valueRequired, _visibleInHelp, _visitor, flagStartString(), ignoreNameString(), nameStartString(), and toString().
~Arg()
TCLAP::Arg::~Arg () inline virtual
Destructor.
Definition at line 483 of file Arg.h.
Member Function Documentation
_checkWithVisitor()
void TCLAP::Arg::_checkWithVisitor () const inline protected
Performs the special handling described by the Visitor.
Definition at line 553 of file Arg.h.
References _visitor.
Referenced by TCLAP::MultiArg< T >::processArg(), TCLAP::MultiSwitchArg::processArg(), TCLAP::UnlabeledMultiArg< T >::processArg(), TCLAP::UnlabeledValueArg< T >::processArg(), and TCLAP::ValueArg< T >::processArg().
_hasBlanks()
bool TCLAP::Arg::_hasBlanks (const std::string & s) const inline
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
Implementation of _hasBlanks.
If so, return true, otherwise return false.
Parameters
s - string to be checked.
Definition at line 577 of file Arg.h.
References blankChar().
Referenced by TCLAP::MultiArg< T >::processArg(), TCLAP::UnlabeledMultiArg< T >::processArg(), TCLAP::UnlabeledValueArg< T >::processArg(), and TCLAP::ValueArg< T >::processArg().
acceptsMultipleValues()
bool TCLAP::Arg::acceptsMultipleValues () inline virtual
Use by output classes to determine whether an Arg accepts multiple values.
Definition at line 593 of file Arg.h.
References _acceptsMultipleValues.
Referenced by TCLAP::DocBookOutput::printShortArg().
addToList()
void TCLAP::Arg::addToList (std::list< Arg * > & argList) const inline virtual
Adds this to the specified list of Args.
Overridden by Args that need to added to the end of the list.
Parameters
argList - The list to add this to.
Reimplemented in TCLAP::UnlabeledMultiArg< T >, and TCLAP::UnlabeledValueArg< T >.
Definition at line 587 of file Arg.h.
Referenced by TCLAP::CmdLine::addToArgList().
allowMore()
bool TCLAP::Arg::allowMore () inline virtual
Used for MultiArgs to determine whether args can still be set.
Reimplemented in TCLAP::MultiArg< T >.
Definition at line 591 of file Arg.h.
argMatches()
bool TCLAP::Arg::argMatches (const std::string & s) const inline virtual
A method that tests whether a string matches this argument.
This is generally called by the processArg() method. This method could be re-implemented by a child to change how arguments are specified on the command line.
Parameters
s - The string to be compared to the flag/name to determine whether the arg matches.
Definition at line 535 of file Arg.h.
References _flag, _name, flagStartString(), and nameStartString().
Referenced by TCLAP::MultiArg< T >::processArg(), TCLAP::MultiSwitchArg::processArg(), TCLAP::SwitchArg::processArg(), and TCLAP::ValueArg< T >::processArg().
blankChar()
static char TCLAP::Arg::blankChar () inline static
The char used as a place holder when SwitchArgs are combined.
Currently set to the bell char (ASCII 7).
Definition at line 192 of file Arg.h.
Referenced by TCLAP::CmdLine::_emptyCombined(), _hasBlanks(), and TCLAP::SwitchArg::combinedSwitchesMatch().
delimiter()
static char TCLAP::Arg::delimiter () inline static
The delimiter that separates an argument flag/name from the value.
Definition at line 186 of file Arg.h.
Referenced by TCLAP::SwitchArg::combinedSwitchesMatch(), longID(), TCLAP::MultiArg< T >::processArg(), TCLAP::ValueArg< T >::processArg(), shortID(), and trimFlag().
flagStartChar()
static char TCLAP::Arg::flagStartChar () inline static
Definition at line 201 of file Arg.h.
References TCLAP_FLAGSTARTCHAR.
Referenced by TCLAP::CmdLine::_emptyCombined(), TCLAP::DocBookOutput::printLongArg(), and TCLAP::DocBookOutput::printShortArg().
flagStartString()
static const std::string TCLAP::Arg::flagStartString () inline static
Definition at line 211 of file Arg.h.
References TCLAP_FLAGSTARTSTRING.
Referenced by TCLAP::StdOutput::_shortUsage(), Arg(), argMatches(), TCLAP::SwitchArg::combinedSwitchesMatch(), longID(), shortID(), and toString().
getDescription() [1/2]
std::string TCLAP::Arg::getDescription () const inline
Returns the argument description.
Definition at line 262 of file Arg.h.
References _required, and getDescription().
Referenced by TCLAP::StdOutput::_longUsage(), getDescription(), TCLAP::UnlabeledMultiArg< T >::operator==(), TCLAP::UnlabeledValueArg< T >::operator==(), and TCLAP::DocBookOutput::printLongArg().
getDescription() [2/2]
std::string TCLAP::Arg::getDescription (bool required) const inline
Returns the argument description.
Parameters
required if the argument should be treated as required when described.
Definition at line 270 of file Arg.h.
References _description, and _requireLabel.
getFlag()
const std::string & TCLAP::Arg::getFlag () const inline
Returns the argument flag.
Definition at line 523 of file Arg.h.
References _flag.
Referenced by TCLAP::internal::CompareShortID(), TCLAP::internal::IsVisibleLongSwitch(), TCLAP::internal::IsVisibleShortSwitch(), TCLAP::DocBookOutput::printLongArg(), and TCLAP::DocBookOutput::printShortArg().
getName()
const std::string & TCLAP::Arg::getName () const inline
Returns the argument name.
Definition at line 525 of file Arg.h.
References _name.
Referenced by TCLAP::StdOutput::_shortUsage(), TCLAP::internal::IsVisibleLongSwitch(), TCLAP::internal::IsVisibleOption(), TCLAP::internal::IsVisibleShortSwitch(), TCLAP::UnlabeledMultiArg< T >::longID(), TCLAP::UnlabeledValueArg< T >::longID(), TCLAP::UnlabeledMultiArg< T >::operator==(), TCLAP::UnlabeledValueArg< T >::operator==(), TCLAP::DocBookOutput::printLongArg(), TCLAP::DocBookOutput::printShortArg(), TCLAP::UnlabeledMultiArg< T >::shortID(), and TCLAP::UnlabeledValueArg< T >::shortID().
hasLabel()
virtual bool TCLAP::Arg::hasLabel () const inline virtual
Reimplemented in TCLAP::UnlabeledMultiArg< T >, and TCLAP::UnlabeledValueArg< T >.
Definition at line 374 of file Arg.h.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), and TCLAP::internal::IsVisibleOption().
hideFromHelp()
virtual void TCLAP::Arg::hideFromHelp (bool hide = true) inline virtual
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
Definition at line 367 of file Arg.h.
References _visibleInHelp.
ignoreNameString()
static const std::string TCLAP::Arg::ignoreNameString () inline static
The name used to identify the ignore rest argument.
Definition at line 225 of file Arg.h.
Referenced by TCLAP::StdOutput::_shortUsage(), Arg(), TCLAP::internal::IsVisibleLongSwitch(), TCLAP::internal::IsVisibleOption(), and TCLAP::internal::IsVisibleShortSwitch().
isIgnoreable()
bool TCLAP::Arg::isIgnoreable () const inline
Indicates whether the argument can be ignored, if desired.
Definition at line 533 of file Arg.h.
References _ignoreable.
Referenced by TCLAP::CmdLine::parse().
isRequired()
bool TCLAP::Arg::isRequired () const inline virtual
Indicates whether the argument is required.
Definition at line 527 of file Arg.h.
References _required.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), TCLAP::ExclusiveArgGroup::add(), TCLAP::CmdLine::addToArgList(), TCLAP::CmdLine::parse(), and TCLAP::DocBookOutput::printLongArg().
isSet()
bool TCLAP::Arg::isSet () const inline
Indicates whether the argument has already been set.
Only true if the arg has been matched on the command line.
Definition at line 531 of file Arg.h.
References _alreadySet.
Referenced by TCLAP::CmdLine::parse().
isValueRequired()
bool TCLAP::Arg::isValueRequired () const inline
Indicates whether a value must be specified for argument.
Definition at line 529 of file Arg.h.
References _valueRequired.
Referenced by TCLAP::StdOutput::_shortUsage(), TCLAP::internal::IsVisibleLongSwitch(), TCLAP::internal::IsVisibleOption(), TCLAP::internal::IsVisibleShortSwitch(), TCLAP::DocBookOutput::printLongArg(), and TCLAP::DocBookOutput::printShortArg().
longID()
std::string TCLAP::Arg::longID (const std::string & valueId = "val") const inline virtual
Returns a long ID for the usage.
Parameters
valueId - The value used in the id.
Reimplemented in TCLAP::MultiArg< T >, TCLAP::MultiSwitchArg, TCLAP::UnlabeledMultiArg< T >, TCLAP::UnlabeledValueArg< T >, and TCLAP::ValueArg< T >.
Definition at line 498 of file Arg.h.
References _flag, _name, _valueRequired, delimiter(), flagStartString(), and nameStartString().
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::ArgGroup::add(), TCLAP::ExclusiveArgGroup::add(), TCLAP::StandaloneArgs::add(), TCLAP::CmdLine::addToArgList(), TCLAP::MultiArg< T >::longID(), TCLAP::MultiSwitchArg::longID(), and TCLAP::ValueArg< T >::longID().
nameStartString()
static const std::string TCLAP::Arg::nameStartString () inline static
Definition at line 220 of file Arg.h.
References TCLAP_NAMESTARTSTRING.
Referenced by Arg(), argMatches(), TCLAP::SwitchArg::combinedSwitchesMatch(), TCLAP::StdOutput::failure(), longID(), TCLAP::DocBookOutput::printLongArg(), TCLAP::DocBookOutput::printShortArg(), shortID(), and toString().
operator==()
bool TCLAP::Arg::operator== (const Arg & a) const inline virtual
Operator ==.
Equality operator. Must be virtual to handle unlabeled args.
Parameters
a - The Arg to be compared to this.
Reimplemented in TCLAP::UnlabeledMultiArg< T >, and TCLAP::UnlabeledValueArg< T >.
Definition at line 516 of file Arg.h.
References _flag, and _name.
processArg()
virtual bool TCLAP::Arg::processArg (int * i, std::vector< std::string > & args) pure virtual
Pure virtual method meant to handle the parsing and value assignment of the string on the command line.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. What is passed in from main.
Implemented in TCLAP::MultiArg< T >, TCLAP::MultiSwitchArg, TCLAP::SwitchArg, TCLAP::UnlabeledMultiArg< T >, TCLAP::UnlabeledValueArg< T >, and TCLAP::ValueArg< T >.
Referenced by TCLAP::CmdLine::parse().
reset()
void TCLAP::Arg::reset () inline virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented in TCLAP::MultiArg< T >, TCLAP::MultiSwitchArg, TCLAP::SwitchArg, and TCLAP::ValueArg< T >.
Definition at line 595 of file Arg.h.
References _alreadySet.
Referenced by TCLAP::MultiArg< T >::reset(), TCLAP::SwitchArg::reset(), and TCLAP::ValueArg< T >::reset().
setBy()
const std::string & TCLAP::Arg::setBy () const inline
Returns the value specified to set this flag (like -a or –all).
Definition at line 293 of file Arg.h.
References _setBy.
Referenced by TCLAP::ExclusiveArgGroup::validate().
setDelimiter()
static void TCLAP::Arg::setDelimiter (char c) inline static
Sets the delimiter for all arguments.
Parameters
c - The character that delimits flags/names from values.
Definition at line 231 of file Arg.h.
shortID()
std::string TCLAP::Arg::shortID (const std::string & valueId = "val") const inline virtual
Returns a short ID for the usage.
Parameters
valueId - The value used in the id.
Reimplemented in TCLAP::MultiArg< T >, TCLAP::MultiSwitchArg, TCLAP::UnlabeledMultiArg< T >, TCLAP::UnlabeledValueArg< T >, and TCLAP::ValueArg< T >.
Definition at line 485 of file Arg.h.
References _flag, _name, _valueRequired, delimiter(), flagStartString(), and nameStartString().
Referenced by TCLAP::StdOutput::_shortUsage(), TCLAP::internal::CompareShortID(), TCLAP::DocBookOutput::printLongArg(), TCLAP::DocBookOutput::printShortArg(), TCLAP::MultiArg< T >::shortID(), TCLAP::MultiSwitchArg::shortID(), and TCLAP::ValueArg< T >::shortID().
toString()
std::string TCLAP::Arg::toString () const inline virtual
Returns a simple string representation of the argument.
Primarily for debugging.
Definition at line 543 of file Arg.h.
References _flag, _name, flagStartString(), and nameStartString().
Referenced by TCLAP::MultiArg< T >::_extractValue(), TCLAP::ValueArg< T >::_extractValue(), Arg(), TCLAP::MultiArg< T >::processArg(), TCLAP::SwitchArg::processArg(), TCLAP::ValueArg< T >::processArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), and TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg().
trimFlag()
void TCLAP::Arg::trimFlag (std::string & flag, std::string & value) const inline virtual
Trims a value off of the flag.
Implementation of trimFlag.
Parameters
flag - The string from which the flag and value will be trimmed. Contains the flag once the value has been trimmed.
value - Where the value trimmed from the string will be stored.
Definition at line 560 of file Arg.h.
References delimiter().
Referenced by TCLAP::MultiArg< T >::processArg(), and TCLAP::ValueArg< T >::processArg().
visibleInHelp()
virtual bool TCLAP::Arg::visibleInHelp () const inline virtual
Returns true if this Arg is visible in the help output.
Definition at line 372 of file Arg.h.
References _visibleInHelp.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), TCLAP::internal::IsVisibleLongSwitch(), TCLAP::internal::IsVisibleOption(), TCLAP::internal::IsVisibleShortSwitch(), and TCLAP::DocBookOutput::printLongArg().
Member Data Documentation
_acceptsMultipleValues
bool TCLAP::Arg::_acceptsMultipleValues protected
Definition at line 141 of file Arg.h.
Referenced by acceptsMultipleValues(), Arg(), TCLAP::MultiArg< T >::MultiArg(), TCLAP::MultiArg< T >::MultiArg(), TCLAP::MultiArg< T >::MultiArg(), and TCLAP::MultiArg< T >::MultiArg().
_alreadySet
bool TCLAP::Arg::_alreadySet protected
Indicates whether the argument has been set.
Indicates that a value on the command line has matched the name/flag of this argument and the values have been set accordingly.
Definition at line 122 of file Arg.h.
Referenced by Arg(), isSet(), TCLAP::MultiArg< T >::processArg(), TCLAP::MultiSwitchArg::processArg(), TCLAP::UnlabeledMultiArg< T >::processArg(), TCLAP::UnlabeledValueArg< T >::processArg(), TCLAP::ValueArg< T >::processArg(), and reset().
_description
std::string TCLAP::Arg::_description protected
Description of the argument.
Definition at line 97 of file Arg.h.
Referenced by Arg(), getDescription(), TCLAP::UnlabeledMultiArg< T >::operator==(), and TCLAP::UnlabeledValueArg< T >::operator==().
_flag
std::string TCLAP::Arg::_flag protected
The single char flag used to identify the argument.
This value (preceded by a dash {-}), can be used to identify an argument on the command line. The _flag can be blank, in fact this is how unlabeled args work. Unlabeled args must override appropriate functions to get correct handling. Note that the _flag does NOT include the dash as part of the flag.
Definition at line 83 of file Arg.h.
Referenced by Arg(), argMatches(), TCLAP::SwitchArg::combinedSwitchesMatch(), getFlag(), longID(), operator==(), shortID(), and toString().
_ignoreable
bool TCLAP::Arg::_ignoreable protected
Whether this argument can be ignored, if desired.
Definition at line 139 of file Arg.h.
Referenced by Arg(), isIgnoreable(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), and TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg().
_name
std::string TCLAP::Arg::_name protected
A single word namd identifying the argument.
This value (preceded by two dashed {–}) can also be used to identify an argument on the command line. Note that the _name does NOT include the two dashes as part of the _name. The _name cannot be blank.
Definition at line 92 of file Arg.h.
Referenced by Arg(), argMatches(), getName(), longID(), operator==(), TCLAP::UnlabeledMultiArg< T >::operator==(), TCLAP::UnlabeledValueArg< T >::operator==(), shortID(), and toString().
_required
const bool TCLAP::Arg::_required protected
Indicating whether the argument is required.
Definition at line 102 of file Arg.h.
Referenced by Arg(), getDescription(), and isRequired().
_requireLabel
std::string TCLAP::Arg::_requireLabel protected
Label to be used in usage description.
Normally set to "required", but can be changed when necessary.
Definition at line 108 of file Arg.h.
Referenced by Arg(), and getDescription().
_setBy
std::string TCLAP::Arg::_setBy protected
Indicates the value specified to set this flag (like -a or –all).
Definition at line 126 of file Arg.h.
Referenced by Arg(), TCLAP::SwitchArg::combinedSwitchesMatch(), TCLAP::MultiArg< T >::processArg(), TCLAP::MultiSwitchArg::processArg(), TCLAP::SwitchArg::processArg(), TCLAP::UnlabeledMultiArg< T >::processArg(), TCLAP::UnlabeledValueArg< T >::processArg(), TCLAP::ValueArg< T >::processArg(), and setBy().
_valueRequired
bool TCLAP::Arg::_valueRequired protected
Indicates whether a value is required for the argument.
Note that the value may be required but the argument/value combination may not be, as specified by _required.
Definition at line 115 of file Arg.h.
Referenced by Arg(), isValueRequired(), longID(), and shortID().
_visibleInHelp
bool TCLAP::Arg::_visibleInHelp protected
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Definition at line 147 of file Arg.h.
Referenced by Arg(), hideFromHelp(), and visibleInHelp().
_visitor
Visitor* TCLAP::Arg::_visitor protected
A pointer to a visitor object.
The visitor allows special handling to occur as soon as the argument is matched. This defaults to NULL and should not be used unless absolutely necessary.
Definition at line 134 of file Arg.h.
Referenced by _checkWithVisitor(), and Arg().
The documentation for this class was generated from the following file:
Arg.h