tclap: TCLAP::SwitchArg Class Reference
TCLAP::SwitchArg Class Reference
A simple switch argument.
#include <SwitchArg.h>
Public Member Functions
SwitchArg (const std::string &flag, const std::string &name, const std::string &desc, bool def=false, Visitor *v=NULL)
SwitchArg constructor.
SwitchArg (const std::string &flag, const std::string &name, const std::string &desc, ArgContainer &parser, bool def=false, Visitor *v=NULL)
SwitchArg constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
bool combinedSwitchesMatch (std::string &combined)
Checks a string to see if any of the chars in the string match the flag for this Switch.
bool getValue () const
Returns bool, whether or not the switch has been set.
operator bool () const
A SwitchArg can be used as a boolean, indicating whether or not the switch has been set.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual std::string shortID (const std::string &valueId="val") const
Returns a short ID for the usage.
virtual std::string longID (const std::string &valueId="val") const
Returns a long ID for the usage.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
virtual bool hasLabel () const
Protected Attributes
bool _value
The value of the switch.
bool _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Detailed Description
A simple switch argument.
If the switch is set on the command line, then the getValue method will return the opposite of the default value for the switch.
Definition at line 40 of file SwitchArg.h.
Constructor & Destructor Documentation
SwitchArg() [1/2]
TCLAP::SwitchArg::SwitchArg (const std::string & flag, const std::string & name, const std::string & desc, bool def = false, Visitor * v = NULL) inline
SwitchArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
def - The default value for this Switch.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 132 of file SwitchArg.h.
References _default, and _value.
Referenced by TCLAP::MultiSwitchArg::MultiSwitchArg(), and TCLAP::MultiSwitchArg::MultiSwitchArg().
SwitchArg() [2/2]
TCLAP::SwitchArg::SwitchArg (const std::string & flag, const std::string & name, const std::string & desc, ArgContainer & parser, bool def = false, Visitor * v = NULL) inline
SwitchArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
parser - A CmdLine parser object to add this Arg to
def - The default value for this Switch.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 139 of file SwitchArg.h.
References _default, _value, and TCLAP::ArgContainer::add().
Member Function Documentation
combinedSwitchesMatch()
bool TCLAP::SwitchArg::combinedSwitchesMatch (std::string & combined) inline
Checks a string to see if any of the chars in the string match the flag for this Switch.
Definition at line 155 of file SwitchArg.h.
References TCLAP::Arg::_flag, TCLAP::Arg::_setBy, TCLAP::Arg::blankChar(), TCLAP::Arg::delimiter(), TCLAP::Arg::flagStartString(), and TCLAP::Arg::nameStartString().
Referenced by TCLAP::MultiSwitchArg::processArg(), and processArg().
getValue()
bool TCLAP::SwitchArg::getValue () const inline
Returns bool, whether or not the switch has been set.
Definition at line 105 of file SwitchArg.h.
References _value.
operator bool()
TCLAP::SwitchArg::operator bool () const inline
A SwitchArg can be used as a boolean, indicating whether or not the switch has been set.
This is the same as calling getValue()
Definition at line 112 of file SwitchArg.h.
References _value.
processArg()
bool TCLAP::SwitchArg::processArg (int * i, std::vector< std::string > & args) inline virtual
Handles the processing of the argument.
This re-implements the Arg version of this method to set the _value of the argument appropriately.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed in from main().
Implements TCLAP::Arg.
Reimplemented in TCLAP::MultiSwitchArg.
Definition at line 203 of file SwitchArg.h.
References TCLAP::Arg::_setBy, TCLAP::Arg::argMatches(), combinedSwitchesMatch(), and TCLAP::Arg::toString().
reset()
void TCLAP::SwitchArg::reset () inline virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::MultiSwitchArg.
Definition at line 228 of file SwitchArg.h.
References _default, _value, and TCLAP::Arg::reset().
Member Data Documentation
_default
bool TCLAP::SwitchArg::_default protected
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Definition at line 51 of file SwitchArg.h.
Referenced by reset(), SwitchArg(), and SwitchArg().
_value
bool TCLAP::SwitchArg::_value protected
The value of the switch.
Definition at line 45 of file SwitchArg.h.
Referenced by getValue(), operator bool(), reset(), SwitchArg(), and SwitchArg().
The documentation for this class was generated from the following file:
SwitchArg.h