tclap: TCLAP::Visitor Class Reference
TCLAP::Visitor Class Reference abstract
A base class that defines the interface for visitors.
#include <Visitor.h>
Public Member Functions
Visitor ()
Constructor.
virtual ~Visitor ()
Destructor.
virtual void visit ()=0
This method (to implemented by children) will be called when the visitor is visited.
Detailed Description
A base class that defines the interface for visitors.
Definition at line 32 of file Visitor.h.
Constructor & Destructor Documentation
Visitor()
TCLAP::Visitor::Visitor () inline
Constructor.
Does nothing.
Definition at line 37 of file Visitor.h.
Referenced by TCLAP::HelpVisitor::HelpVisitor(), TCLAP::IgnoreRestVisitor::IgnoreRestVisitor(), and TCLAP::VersionVisitor::VersionVisitor().
~Visitor()
virtual TCLAP::Visitor::~Visitor () inline virtual
Destructor.
Does nothing.
Definition at line 42 of file Visitor.h.
Member Function Documentation
visit()
virtual void TCLAP::Visitor::visit () pure virtual
This method (to implemented by children) will be called when the visitor is visited.
Implemented in TCLAP::HelpVisitor, TCLAP::IgnoreRestVisitor, and TCLAP::VersionVisitor.
The documentation for this class was generated from the following file:
Visitor.h