tclap: TCLAP::UnlabeledMultiArg< T > Class Template Reference
TCLAP::UnlabeledMultiArg< T > Class Template Reference
Just like a MultiArg, except that the arguments are unlabeled.
#include <UnlabeledMultiArg.h>
Public Member Functions
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, ArgContainer &parser, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, bool ignoreable=false, Visitor *v=NULL)
Constructor.
UnlabeledMultiArg (const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, ArgContainer &parser, bool ignoreable=false, Visitor *v=NULL)
Constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
virtual std::string shortID (const std::string &) const
Returns the a short id string.
virtual std::string longID (const std::string &) const
Returns the a long id string.
virtual bool operator== (const Arg &a) const
Operator ==.
virtual void addToList (std::list< Arg * > &argList) const
Pushes this to back of list rather than front.
virtual bool hasLabel () const
Public Member Functions inherited from TCLAP::MultiArg< T >
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, ArgContainer &parser, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, ArgContainer &parser, Visitor *v=NULL)
Constructor.
const std::vector< T > & getValue () const
Returns a vector of type T containing the values parsed from the command line.
const_iterator begin () const
Returns an iterator over the values parsed from the command line.
const_iterator end () const
Returns the end of the values parsed from the command line.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
Additional Inherited Members
Public Types inherited from TCLAP::MultiArg< T >
typedef std::vector< T > container_type
typedef container_type::iterator iterator
typedef container_type::const_iterator const_iterator
Static Public Member Functions inherited from TCLAP::Arg
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Protected Member Functions inherited from TCLAP::MultiArg< T >
void _extractValue (const std::string &val)
Extracts the value from the string.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes inherited from TCLAP::MultiArg< T >
std::vector< T > _values
The list of values parsed from the CmdLine.
std::string _typeDesc
The description of type T to be used in the usage.
const Constraint< T > * _constraint
A constraint that the values of this Arg must conform to.
bool _allowMore
Used by MultiArg to decide whether to keep parsing for this arg.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Detailed Description
template<class T>
class TCLAP::UnlabeledMultiArg< T >
Just like a MultiArg, except that the arguments are unlabeled.
Basically, this Arg will slurp up everything that hasn't been matched to another Arg.
Definition at line 42 of file UnlabeledMultiArg.h.
Constructor & Destructor Documentation
UnlabeledMultiArg() [1/4]
template<class T> TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 181 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), TCLAP::MultiArg< T >::MultiArg(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [2/4]
template<class T> TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, ArgContainer & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 191 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::ArgContainer::add(), TCLAP::OptionalUnlabeledTracker::check(), TCLAP::MultiArg< T >::MultiArg(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [3/4]
template<class T> TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const Constraint< T > * constraint, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 203 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), TCLAP::MultiArg< T >::MultiArg(), and TCLAP::Arg::toString().
UnlabeledMultiArg() [4/4]
template<class T> TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg (const std::string & name, const std::string & desc, bool req, const Constraint< T > * constraint, ArgContainer & parser, bool ignoreable = false, Visitor * v = NULL)
Constructor.
Parameters
name - The name of the Arg. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to
ignoreable - Whether or not this argument can be ignored using the "--" flag.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 213 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::ArgContainer::add(), TCLAP::OptionalUnlabeledTracker::check(), TCLAP::MultiArg< T >::MultiArg(), and TCLAP::Arg::toString().
Member Function Documentation
addToList()
template<class T> void TCLAP::UnlabeledMultiArg< T >::addToList (std::list< Arg * > & argList) const virtual
Pushes this to back of list rather than front.
Parameters
argList - The list this should be added to.
Reimplemented from TCLAP::Arg.
Definition at line 256 of file UnlabeledMultiArg.h.
hasLabel()
template<class T> virtual bool TCLAP::UnlabeledMultiArg< T >::hasLabel () const inline virtual
Reimplemented from TCLAP::Arg.
Definition at line 177 of file UnlabeledMultiArg.h.
longID()
template<class T> virtual std::string TCLAP::UnlabeledMultiArg< T >::longID (const std::string &) const inline virtual
Returns the a long id string.
Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::MultiArg< T >.
Definition at line 160 of file UnlabeledMultiArg.h.
References TCLAP::MultiArg< T >::_typeDesc, and TCLAP::Arg::getName().
operator==()
template<class T> bool TCLAP::UnlabeledMultiArg< T >::operator== (const Arg & a) const virtual
Operator ==.
Parameters
a - The Arg to be compared to this.
Reimplemented from TCLAP::Arg.
Definition at line 248 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_description, TCLAP::Arg::_name, TCLAP::Arg::getDescription(), and TCLAP::Arg::getName().
processArg()
template<class T> bool TCLAP::UnlabeledMultiArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument.
This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed from main().
Reimplemented from TCLAP::MultiArg< T >.
Definition at line 225 of file UnlabeledMultiArg.h.
References TCLAP::Arg::_alreadySet, TCLAP::Arg::_checkWithVisitor(), TCLAP::MultiArg< T >::_extractValue(), TCLAP::Arg::_hasBlanks(), and TCLAP::Arg::_setBy.
shortID()
template<class T> virtual std::string TCLAP::UnlabeledMultiArg< T >::shortID (const std::string &) const inline virtual
Returns the a short id string.
Used in the usage.
Reimplemented from TCLAP::MultiArg< T >.
Definition at line 152 of file UnlabeledMultiArg.h.
References TCLAP::Arg::getName().
The documentation for this class was generated from the following file:
UnlabeledMultiArg.h