tclap: TCLAP::CmdLine Class Reference
TCLAP::CmdLine Class Reference
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
#include <CmdLine.h>
Public Member Functions
CmdLine (const std::string &message, const char delimiter=' ', const std::string &version="none", bool helpAndVersion=true)
Command line constructor.
virtual ~CmdLine ()
Deletes any resources allocated by a CmdLine object.
ArgContainer & add (Arg &a)
Adds an argument to the list of arguments to be parsed.
ArgContainer & add (Arg *a)
An alternative add.
ArgContainer & add (ArgGroup &args)
Adds an argument group to the list of arguments to be parsed.
void addToArgList (Arg *a)
void xorAdd (Arg &a, Arg &b)
void xorAdd (const std::vector< Arg * > &xors)
void parse (int argc, const char *const *argv)
Parses the command line.
void parse (std::vector< std::string > &args)
Parses the command line.
void setOutput (CmdLineOutput *co)
std::string getVersion () const
Returns the version string.
std::string getProgramName () const
Returns the program name string.
std::list< Arg * > getArgList () const
std::list< ArgGroup * > getArgGroups ()
Returns the list of ArgGroups.
char getDelimiter () const
Returns the delimiter string.
std::string getMessage () const
Returns the message string.
bool hasHelpAndVersion () const
Indicates whether or not the help and version switches were created automatically.
void setExceptionHandling (const bool state)
Disables or enables CmdLine's internal parsing exception handling.
bool hasExceptionHandling () const
Returns the current state of the internal exception handling.
void reset ()
Allows the CmdLine object to be reused.
void ignoreUnmatched (const bool ignore)
Allows unmatched args to be ignored.
void beginIgnoring ()
Begin ignoring arguments since the "--" argument was specified.
bool ignoreRest ()
Whether to ignore the rest.
Public Member Functions inherited from TCLAP::CmdLineInterface
virtual ~CmdLineInterface ()
Destructor.
void parse (std::vector< std::string > &args)
Parses the command line.
Public Member Functions inherited from TCLAP::ArgContainer
virtual ~ArgContainer ()
Protected Member Functions
void missingArgsException (const std::list< ArgGroup * > &missing)
Throws an exception listing the missing args.
bool _emptyCombined (const std::string &s)
Checks whether a name/flag string matches entirely matches the Arg::blankChar.
Protected Attributes
std::list< Arg * > _argList
The list of arguments that will be tested against the command line.
StandaloneArgs _standaloneArgs
StandaloneArgs _autoArgs
std::list< ArgGroup * > _argGroups
Some args have set constraints on them (i.e., exactly or at most one must be specified.
std::string _progName
The name of the program.
std::string _message
A message used to describe the program.
std::string _version
The version to be displayed with the –version switch.
int _numRequired
The number of arguments that are required to be present on the command line.
char _delimiter
The character that is used to separate the argument flag/name from the value.
DeferDelete _deleteOnExit
Add pointers that should be deleted as part of cleanup when this object is destroyed.
StdOutput _defaultOutput
Default output handler if nothing is specified.
CmdLineOutput * _output
Object that handles all output for the CmdLine.
bool _handleExceptions
Should CmdLine handle parsing exceptions internally?
Detailed Description
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
Definition at line 82 of file CmdLine.h.
Constructor & Destructor Documentation
CmdLine()
TCLAP::CmdLine::CmdLine (const std::string & message, const char delimiter = ' ', const std::string & version = "none", bool helpAndVersion = true) inline
Command line constructor.
Defines how the arguments will be parsed.
Parameters
message - The message to be used in the usage output.
delimiter - The character that is used to separate the argument flag/name from the value. Defaults to ' ' (space).
version - The version number to be used in the –version switch.
helpAndVersion - Whether or not to create the Help and Version switches. Defaults to true.
Definition at line 320 of file CmdLine.h.
References _argGroups, _argList, _autoArgs, _defaultOutput, _deleteOnExit, _delimiter, _handleExceptions, _message, _numRequired, _output, _progName, _standaloneArgs, and _version.
~CmdLine()
virtual TCLAP::CmdLine::~CmdLine () inline virtual
Deletes any resources allocated by a CmdLine object.
Definition at line 209 of file CmdLine.h.
Member Function Documentation
_emptyCombined()
bool TCLAP::CmdLine::_emptyCombined (const std::string & s) inline protected
Checks whether a name/flag string matches entirely matches the Arg::blankChar.
Used when multiple switches are combined into a single argument.
Parameters
s - The message to be used in the usage.
Definition at line 545 of file CmdLine.h.
References TCLAP::Arg::blankChar(), and TCLAP::Arg::flagStartChar().
Referenced by parse().
add() [1/3]
ArgContainer & TCLAP::CmdLine::add (Arg & a) inline virtual
Adds an argument to the list of arguments to be parsed.
Parameters
a - Argument to be added.
Return values
A reference to this so that add calls can be chained
Implements TCLAP::CmdLineInterface.
Definition at line 405 of file CmdLine.h.
References add().
Referenced by add().
add() [2/3]
ArgContainer & TCLAP::CmdLine::add (Arg * a) inline virtual
An alternative add.
Functionally identical.
Parameters
a - Argument to be added.
Return values
A reference to this so that add calls can be chained
Implements TCLAP::CmdLineInterface.
Definition at line 420 of file CmdLine.h.
References _standaloneArgs, and addToArgList().
add() [3/3]
ArgContainer & TCLAP::CmdLine::add (ArgGroup & args) inline virtual
Adds an argument group to the list of arguments to be parsed.
All arguments in the group are added and the ArgGroup object will validate that the input matches its constraints.
Parameters
args - Argument group to be added.
Return values
A reference to this so that add calls can be chained
Implements TCLAP::CmdLineInterface.
Definition at line 398 of file CmdLine.h.
References _argGroups, and TCLAP::ArgGroup::setParser().
addToArgList()
void TCLAP::CmdLine::addToArgList (Arg * a) inline virtual
Implements TCLAP::CmdLineInterface.
Definition at line 409 of file CmdLine.h.
References _argList, _numRequired, TCLAP::Arg::addToList(), TCLAP::Arg::isRequired(), and TCLAP::Arg::longID().
Referenced by add().
beginIgnoring()
void TCLAP::CmdLine::beginIgnoring () inline virtual
Begin ignoring arguments since the "--" argument was specified.
Implements TCLAP::CmdLineInterface.
Definition at line 312 of file CmdLine.h.
getArgGroups()
std::list< ArgGroup * > TCLAP::CmdLine::getArgGroups () inline virtual
Returns the list of ArgGroups.
Implements TCLAP::CmdLineInterface.
Definition at line 274 of file CmdLine.h.
References _argGroups, and _autoArgs.
getArgList()
std::list< Arg * > TCLAP::CmdLine::getArgList () const inline virtual
Implements TCLAP::CmdLineInterface.
Definition at line 273 of file CmdLine.h.
References _argList.
getDelimiter()
char TCLAP::CmdLine::getDelimiter () const inline virtual
Returns the delimiter string.
Implements TCLAP::CmdLineInterface.
Definition at line 280 of file CmdLine.h.
References _delimiter.
getMessage()
std::string TCLAP::CmdLine::getMessage () const inline virtual
Returns the message string.
Implements TCLAP::CmdLineInterface.
Definition at line 281 of file CmdLine.h.
References _message.
getProgramName()
std::string TCLAP::CmdLine::getProgramName () const inline virtual
Returns the program name string.
Implements TCLAP::CmdLineInterface.
Definition at line 270 of file CmdLine.h.
References _progName.
getVersion()
std::string TCLAP::CmdLine::getVersion () const inline virtual
Returns the version string.
Implements TCLAP::CmdLineInterface.
Definition at line 268 of file CmdLine.h.
References _version.
hasExceptionHandling()
bool TCLAP::CmdLine::hasExceptionHandling () const inline
Returns the current state of the internal exception handling.
Return values
true Parsing exceptions are handled internally.
false Parsing exceptions are propagated to the caller.
Definition at line 297 of file CmdLine.h.
References _handleExceptions.
hasHelpAndVersion()
bool TCLAP::CmdLine::hasHelpAndVersion () const inline virtual
Indicates whether or not the help and version switches were created automatically.
Implements TCLAP::CmdLineInterface.
Definition at line 282 of file CmdLine.h.
ignoreRest()
bool TCLAP::CmdLine::ignoreRest () inline virtual
Whether to ignore the rest.
Implements TCLAP::CmdLineInterface.
Definition at line 313 of file CmdLine.h.
Referenced by parse().
ignoreUnmatched()
void TCLAP::CmdLine::ignoreUnmatched (const bool ignore) inline
Allows unmatched args to be ignored.
By default false.
Parameters
ignore If true the cmdline will ignore any unmatched args and if false it will behave as normal.
Definition at line 601 of file CmdLine.h.
missingArgsException()
void TCLAP::CmdLine::missingArgsException (const std::list< ArgGroup * > & missing) inline protected
Throws an exception listing the missing args.
Definition at line 554 of file CmdLine.h.
References _argList.
Referenced by parse().
parse() [1/2]
void TCLAP::CmdLine::parse (int argc, const char *const * argv) inline virtual
Parses the command line.
Parameters
argc - Number of arguments.
argv - Array of arguments.
Implements TCLAP::CmdLineInterface.
Definition at line 427 of file CmdLine.h.
References parse().
Referenced by parse().
parse() [2/2]
void TCLAP::CmdLine::parse (std::vector< std::string > & args) inline
Parses the command line.
Parameters
args - A vector of strings representing the args. args[0] is still the program name.
Definition at line 436 of file CmdLine.h.
References _argGroups, _argList, _emptyCombined(), _handleExceptions, _numRequired, _output, _progName, TCLAP::basename(), TCLAP::ExitException::getExitStatus(), ignoreRest(), TCLAP::Arg::isIgnoreable(), TCLAP::Arg::isRequired(), TCLAP::Arg::isSet(), missingArgsException(), and TCLAP::Arg::processArg().
reset()
void TCLAP::CmdLine::reset () inline virtual
Allows the CmdLine object to be reused.
Implements TCLAP::CmdLineInterface.
Definition at line 593 of file CmdLine.h.
References _argList, and _progName.
setExceptionHandling()
void TCLAP::CmdLine::setExceptionHandling (const bool state) inline
Disables or enables CmdLine's internal parsing exception handling.
Parameters
state Should CmdLine handle parsing exceptions internally?
Definition at line 589 of file CmdLine.h.
References _handleExceptions.
setOutput()
void TCLAP::CmdLine::setOutput (CmdLineOutput * co) inline virtual
Parameters
co - CmdLineOutput object that we want to use instead.
Implements TCLAP::CmdLineInterface.
Definition at line 587 of file CmdLine.h.
References _output.
xorAdd() [1/2]
void TCLAP::CmdLine::xorAdd (Arg & a, Arg & b) inline virtual
Deprecated
Use OneOf instead.
Implements TCLAP::CmdLineInterface.
Definition at line 391 of file CmdLine.h.
References xorAdd().
Referenced by xorAdd().
xorAdd() [2/2]
void TCLAP::CmdLine::xorAdd (const std::vector< Arg * > & xors) inline virtual
Deprecated
Use OneOf instead.
Implements TCLAP::CmdLineInterface.
Definition at line 381 of file CmdLine.h.
References _deleteOnExit, and TCLAP::ExclusiveArgGroup::add().
Member Data Documentation
_argGroups
std::list<ArgGroup *> TCLAP::CmdLine::_argGroups protected
Some args have set constraints on them (i.e., exactly or at most one must be specified.
Definition at line 97 of file CmdLine.h.
Referenced by add(), CmdLine(), getArgGroups(), and parse().
_argList
std::list<Arg *> TCLAP::CmdLine::_argList protected
The list of arguments that will be tested against the command line.
Definition at line 88 of file CmdLine.h.
Referenced by addToArgList(), CmdLine(), getArgList(), missingArgsException(), parse(), and reset().
_autoArgs
StandaloneArgs TCLAP::CmdLine::_autoArgs protected
Definition at line 91 of file CmdLine.h.
Referenced by CmdLine(), and getArgGroups().
_defaultOutput
StdOutput TCLAP::CmdLine::_defaultOutput protected
Default output handler if nothing is specified.
Definition at line 137 of file CmdLine.h.
Referenced by CmdLine().
_deleteOnExit
DeferDelete TCLAP::CmdLine::_deleteOnExit protected
Add pointers that should be deleted as part of cleanup when this object is destroyed.
Definition at line 132 of file CmdLine.h.
Referenced by CmdLine(), and xorAdd().
_delimiter
char TCLAP::CmdLine::_delimiter protected
The character that is used to separate the argument flag/name from the value.
Defaults to ' ' (space).
Definition at line 125 of file CmdLine.h.
Referenced by CmdLine(), and getDelimiter().
_handleExceptions
bool TCLAP::CmdLine::_handleExceptions protected
Should CmdLine handle parsing exceptions internally?
Definition at line 147 of file CmdLine.h.
Referenced by CmdLine(), hasExceptionHandling(), parse(), and setExceptionHandling().
_message
std::string TCLAP::CmdLine::_message protected
A message used to describe the program.
Used in the usage output.
Definition at line 107 of file CmdLine.h.
Referenced by CmdLine(), and getMessage().
_numRequired
int TCLAP::CmdLine::_numRequired protected
The number of arguments that are required to be present on the command line.
This is set dynamically, based on the Args added to the CmdLine object.
Definition at line 119 of file CmdLine.h.
Referenced by addToArgList(), CmdLine(), and parse().
_output
CmdLineOutput* TCLAP::CmdLine::_output protected
Object that handles all output for the CmdLine.
Definition at line 142 of file CmdLine.h.
Referenced by CmdLine(), parse(), and setOutput().
_progName
std::string TCLAP::CmdLine::_progName protected
The name of the program.
Set to argv[0].
Definition at line 102 of file CmdLine.h.
Referenced by CmdLine(), getProgramName(), parse(), and reset().
_standaloneArgs
StandaloneArgs TCLAP::CmdLine::_standaloneArgs protected
Definition at line 90 of file CmdLine.h.
Referenced by add(), and CmdLine().
_version
std::string TCLAP::CmdLine::_version protected
The version to be displayed with the –version switch.
Definition at line 112 of file CmdLine.h.
Referenced by CmdLine(), and getVersion().
The documentation for this class was generated from the following file:
CmdLine.h