tclap: TCLAP::ValueArg< T > Class Template Reference
TCLAP::ValueArg< T > Class Template Reference
The basic labeled argument that parses a value.
#include <ValueArg.h>
Public Member Functions
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, ArgContainer &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const Constraint< T > *constraint, ArgContainer &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const Constraint< T > *constraint, Visitor *v=NULL)
Labeled ValueArg constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
const T & getValue () const
Returns the value of the argument.
operator const T & () const
A ValueArg can be used as as its value type (T) This is the same as calling getValue()
virtual std::string shortID (const std::string &val="val") const
Specialization of shortID.
virtual std::string longID (const std::string &val="val") const
Specialization of longID.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
virtual bool hasLabel () const
Protected Member Functions
void _extractValue (const std::string &val)
Extracts the value from the string.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes
T _value
The value parsed from the command line.
T _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
std::string _typeDesc
A human readable description of the type to be parsed.
const Constraint< T > * _constraint
A Constraint this Arg must conform to.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Detailed Description
template<class T>
class TCLAP::ValueArg< T >
The basic labeled argument that parses a value.
This is a template class, which means the type T defines the type that a given object will attempt to parse when the flag/name is matched on the command line. While there is nothing stopping you from creating an unflagged ValueArg, it is unwise and would cause significant problems. Instead use an UnlabeledValueArg.
Definition at line 45 of file ValueArg.h.
Constructor & Destructor Documentation
ValueArg() [1/4]
template<class T> TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, Visitor * v = NULL)
Labeled ValueArg constructor.
Constructor implementation.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 227 of file ValueArg.h.
References _constraint, _default, _typeDesc, and _value.
Referenced by TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), and TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg().
ValueArg() [2/4]
template<class T> TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, ArgContainer & parser, Visitor * v = NULL)
Labeled ValueArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 237 of file ValueArg.h.
References _constraint, _default, _typeDesc, _value, and TCLAP::ArgContainer::add().
ValueArg() [3/4]
template<class T> TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const Constraint< T > * constraint, ArgContainer & parser, Visitor * v = NULL)
Labeled ValueArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 260 of file ValueArg.h.
References _constraint, _default, _typeDesc, _value, TCLAP::ArgContainer::add(), and shortID().
ValueArg() [4/4]
template<class T> TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const Constraint< T > * constraint, Visitor * v = NULL)
Labeled ValueArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 250 of file ValueArg.h.
References _constraint, _default, _typeDesc, _value, and shortID().
Member Function Documentation
_extractValue()
template<class T> void TCLAP::ValueArg< T >::_extractValue (const std::string & val) protected
Extracts the value from the string.
Attempts to parse string as type T, if this fails an exception is thrown.
Parameters
val - value to be parsed.
Definition at line 330 of file ValueArg.h.
References _constraint, _value, TCLAP::ArgException::error(), TCLAP::ExtractValue(), and TCLAP::Arg::toString().
Referenced by TCLAP::UnlabeledValueArg< T >::processArg(), and processArg().
getValue()
template<class T> const T & TCLAP::ValueArg< T >::getValue () const inline
Returns the value of the argument.
Definition at line 193 of file ValueArg.h.
References _value.
Referenced by operator const T &().
longID()
template<class T> std::string TCLAP::ValueArg< T >::longID (const std::string & val = "val") const virtual
Specialization of longID.
Implementation of longID.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 325 of file ValueArg.h.
References _typeDesc, and TCLAP::Arg::longID().
operator const T &()
template<class T> TCLAP::ValueArg< T >::operator const T & () const inline
A ValueArg can be used as as its value type (T) This is the same as calling getValue()
Definition at line 199 of file ValueArg.h.
References getValue().
processArg()
template<class T> bool TCLAP::ValueArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument.
Implementation of processArg().
This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed in from main().
Implements TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 276 of file ValueArg.h.
References TCLAP::Arg::_alreadySet, TCLAP::Arg::_checkWithVisitor(), _extractValue(), TCLAP::Arg::_hasBlanks(), TCLAP::Arg::_setBy, TCLAP::Arg::argMatches(), TCLAP::Arg::delimiter(), TCLAP::Arg::toString(), and TCLAP::Arg::trimFlag().
reset()
template<class T> void TCLAP::ValueArg< T >::reset () virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented from TCLAP::Arg.
Definition at line 346 of file ValueArg.h.
References _default, _value, and TCLAP::Arg::reset().
shortID()
template<class T> std::string TCLAP::ValueArg< T >::shortID (const std::string & val = "val") const virtual
Specialization of shortID.
Implementation of shortID.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 317 of file ValueArg.h.
References _typeDesc, and TCLAP::Arg::shortID().
Referenced by ValueArg(), and ValueArg().
Member Data Documentation
_constraint
template<class T> const Constraint<T>* TCLAP::ValueArg< T >::_constraint protected
A Constraint this Arg must conform to.
Definition at line 72 of file ValueArg.h.
Referenced by _extractValue(), ValueArg(), ValueArg(), ValueArg(), and ValueArg().
_default
template<class T> T TCLAP::ValueArg< T >::_default protected
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Definition at line 58 of file ValueArg.h.
Referenced by reset(), ValueArg(), ValueArg(), ValueArg(), and ValueArg().
_typeDesc
template<class T> std::string TCLAP::ValueArg< T >::_typeDesc protected
A human readable description of the type to be parsed.
This is a hack, plain and simple. Ideally we would use RTTI to return the name of type T, but until there is some sort of consistent support for human readable names, we are left to our own devices.
Definition at line 67 of file ValueArg.h.
Referenced by TCLAP::UnlabeledValueArg< T >::longID(), longID(), shortID(), ValueArg(), ValueArg(), ValueArg(), and ValueArg().
_value
template<class T> T TCLAP::ValueArg< T >::_value protected
The value parsed from the command line.
Can be of any type, as long as the >> operator for the type is defined.
Definition at line 52 of file ValueArg.h.
Referenced by _extractValue(), getValue(), reset(), ValueArg(), ValueArg(), ValueArg(), and ValueArg().
The documentation for this class was generated from the following file:
ValueArg.h