tclap: TCLAP::DocBookOutput Class Reference
TCLAP::DocBookOutput Class Reference
A class that generates DocBook output for usage() method for the given CmdLine and its Args.
#include <DocBookOutput.h>
Public Member Functions
virtual void usage (CmdLineInterface &c)
Prints the usage to stdout.
virtual void version (CmdLineInterface &c)
Prints the version to stdout.
virtual void failure (CmdLineInterface &c, ArgException &e)
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
DocBookOutput ()
Public Member Functions inherited from TCLAP::CmdLineOutput
virtual ~CmdLineOutput ()
Virtual destructor.
Protected Member Functions
void substituteSpecialChars (std::string &s, char r, const std::string &x) const
Substitutes the char r for string x in string s.
void removeChar (std::string &s, char r) const
void printShortArg (Arg *it, bool required)
void printLongArg (const ArgGroup &it) const
Protected Attributes
char theDelimiter
Detailed Description
A class that generates DocBook output for usage() method for the given CmdLine and its Args.
Definition at line 43 of file DocBookOutput.h.
Constructor & Destructor Documentation
DocBookOutput()
TCLAP::DocBookOutput::DocBookOutput () inline
Definition at line 67 of file DocBookOutput.h.
References theDelimiter.
Member Function Documentation
failure()
void TCLAP::DocBookOutput::failure (CmdLineInterface & c, ArgException & e) inline virtual
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
e - The ArgException that caused the failure.
Implements TCLAP::CmdLineOutput.
Definition at line 187 of file DocBookOutput.h.
References TCLAP::ArgException::what().
printLongArg()
void TCLAP::DocBookOutput::printLongArg (const ArgGroup & it) const inline protected
Definition at line 246 of file DocBookOutput.h.
References TCLAP::ArgGroup::begin(), TCLAP::CountVisibleArgs(), TCLAP::ArgGroup::end(), TCLAP::Arg::flagStartChar(), TCLAP::Arg::getDescription(), TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::Arg::isRequired(), TCLAP::ArgGroup::isRequired(), TCLAP::Arg::isValueRequired(), TCLAP::Arg::nameStartString(), removeChar(), TCLAP::Arg::shortID(), substituteSpecialChars(), theDelimiter, and TCLAP::Arg::visibleInHelp().
Referenced by usage().
printShortArg()
void TCLAP::DocBookOutput::printShortArg (Arg * it, bool required) inline protected
Definition at line 209 of file DocBookOutput.h.
References TCLAP::Arg::acceptsMultipleValues(), TCLAP::Arg::flagStartChar(), TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::Arg::isValueRequired(), TCLAP::Arg::nameStartString(), removeChar(), TCLAP::Arg::shortID(), substituteSpecialChars(), and theDelimiter.
Referenced by usage().
removeChar()
void TCLAP::DocBookOutput::removeChar (std::string & s, char r) const inline protected
Definition at line 202 of file DocBookOutput.h.
Referenced by printLongArg(), and printShortArg().
substituteSpecialChars()
void TCLAP::DocBookOutput::substituteSpecialChars (std::string & s, char r, const std::string & x) const inline protected
Substitutes the char r for string x in string s.
Parameters
s - The string to operate on.
r - The char to replace.
x - What to replace r with.
Definition at line 193 of file DocBookOutput.h.
Referenced by printLongArg(), and printShortArg().
usage()
void TCLAP::DocBookOutput::usage (CmdLineInterface & c) inline virtual
Prints the usage to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 104 of file DocBookOutput.h.
References TCLAP::CountVisibleArgs(), TCLAP::CmdLineInterface::getArgGroups(), TCLAP::CmdLineInterface::getDelimiter(), TCLAP::CmdLineInterface::getMessage(), TCLAP::CmdLineInterface::getProgramName(), TCLAP::CmdLineInterface::getVersion(), TCLAP::internal::GroupChoice(), printLongArg(), printShortArg(), and theDelimiter.
version()
void TCLAP::DocBookOutput::version (CmdLineInterface & c) inline virtual
Prints the version to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 86 of file DocBookOutput.h.
References TCLAP::CmdLineInterface::getVersion().
Member Data Documentation
theDelimiter
char TCLAP::DocBookOutput::theDelimiter protected
Definition at line 83 of file DocBookOutput.h.
Referenced by DocBookOutput(), printLongArg(), printShortArg(), and usage().
The documentation for this class was generated from the following file:
DocBookOutput.h