tclap: TCLAP::StandaloneArgs Class Reference
TCLAP::StandaloneArgs Class Reference
#include <CmdLine.h>
Public Member Functions
StandaloneArgs ()
ArgContainer & add (Arg *arg)
Add an argument to this arg group.
bool showAsGroup () const
If arguments in this group should show up as grouped in help.
Public Member Functions inherited from TCLAP::AnyOf
AnyOf ()
AnyOf (CmdLineInterface &parser)
bool validate ()
Validates that the constraints of the ArgGroup are satisfied.
bool isExclusive () const
Returns true if this argument group is exclusive.
bool isRequired () const
Returns true if this argument group is required.
Public Member Functions inherited from TCLAP::ArgGroup
virtual ~ArgGroup ()
virtual ArgContainer & add (Arg &arg)
Add an argument to this arg group.
void setParser (CmdLineInterface &parser)
Used by the parser to connect itself to this arg group.
const std::string getName () const
Returns the argument group's name.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Public Member Functions inherited from TCLAP::ArgContainer
virtual ~ArgContainer ()
Additional Inherited Members
Public Types inherited from TCLAP::ArgGroup
typedef std::list< Arg * > Container
typedef Container::iterator iterator
typedef Container::const_iterator const_iterator
Protected Member Functions inherited from TCLAP::ArgGroup
ArgGroup ()
Protected Attributes inherited from TCLAP::ArgGroup
CmdLineInterface * _parser
Container _args
Detailed Description
Definition at line 56 of file CmdLine.h.
Constructor & Destructor Documentation
StandaloneArgs()
TCLAP::StandaloneArgs::StandaloneArgs () inline
Definition at line 58 of file CmdLine.h.
Member Function Documentation
add()
ArgContainer & TCLAP::StandaloneArgs::add (Arg * arg) inline virtual
Add an argument to this arg group.
Reimplemented from TCLAP::ArgGroup.
Definition at line 60 of file CmdLine.h.
References TCLAP::ArgGroup::_args, TCLAP::ArgGroup::begin(), TCLAP::ArgGroup::end(), and TCLAP::Arg::longID().
showAsGroup()
bool TCLAP::StandaloneArgs::showAsGroup () const inline virtual
If arguments in this group should show up as grouped in help.
Reimplemented from TCLAP::ArgGroup.
Definition at line 75 of file CmdLine.h.
The documentation for this class was generated from the following file:
CmdLine.h