tclap: TCLAP::ArgContainer Class Reference
TCLAP::ArgContainer Class Reference abstract
Interface that allows adding an Arg to a "container".
#include <ArgContainer.h>
Public Member Functions
virtual ~ArgContainer ()
virtual ArgContainer & add (Arg &a)=0
Adds an argument.
virtual ArgContainer & add (Arg *a)=0
Adds an argument.
Detailed Description
Interface that allows adding an Arg to a "container".
A container does not have to be a container in the C++ standard library sense, just something that wants to hold on to references to Arg's. The container does not own the added Arg's and it is the user's responsibility to ensure the life time (scope) of the Arg's outlives any operations on the container.
Definition at line 39 of file ArgContainer.h.
Constructor & Destructor Documentation
~ArgContainer()
virtual TCLAP::ArgContainer::~ArgContainer () inline virtual
Definition at line 41 of file ArgContainer.h.
Member Function Documentation
add() [1/2]
virtual ArgContainer & TCLAP::ArgContainer::add (Arg & a) pure virtual
Adds an argument.
Ownership is not transfered.
Parameters
a - Argument to be added.
Implemented in TCLAP::ArgGroup, TCLAP::CmdLine, TCLAP::CmdLineInterface, and TCLAP::ExclusiveArgGroup.
Referenced by TCLAP::MultiArg< T >::MultiArg(), TCLAP::MultiArg< T >::MultiArg(), TCLAP::MultiSwitchArg::MultiSwitchArg(), TCLAP::SwitchArg::SwitchArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::ValueArg< T >::ValueArg(), and TCLAP::ValueArg< T >::ValueArg().
add() [2/2]
virtual ArgContainer & TCLAP::ArgContainer::add (Arg * a) pure virtual
Adds an argument.
Ownership is not transfered.
Parameters
a - Argument to be added.
Implemented in TCLAP::ArgGroup, TCLAP::CmdLine, TCLAP::CmdLineInterface, TCLAP::ExclusiveArgGroup, and TCLAP::StandaloneArgs.
The documentation for this class was generated from the following file:
ArgContainer.h