tclap: TCLAP::OptionalUnlabeledTracker Class Reference
TCLAP::OptionalUnlabeledTracker Class Reference
#include <OptionalUnlabeledTracker.h>
Static Public Member Functions
static void check (bool req, const std::string &argName)
static void gotOptional ()
static bool & alreadyOptional ()
Detailed Description
Definition at line 32 of file OptionalUnlabeledTracker.h.
Member Function Documentation
alreadyOptional()
static bool & TCLAP::OptionalUnlabeledTracker::alreadyOptional () inline static
Definition at line 38 of file OptionalUnlabeledTracker.h.
Referenced by check().
check()
void TCLAP::OptionalUnlabeledTracker::check (bool req, const std::string & argName) inline static
Definition at line 47 of file OptionalUnlabeledTracker.h.
References alreadyOptional(), and gotOptional().
Referenced by TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg(), and TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg().
gotOptional()
static void TCLAP::OptionalUnlabeledTracker::gotOptional () inline static
Definition at line 36 of file OptionalUnlabeledTracker.h.
Referenced by check().
The documentation for this class was generated from the following file:
OptionalUnlabeledTracker.h