tclap: TCLAP::MultiArg< T > Class Template Reference
TCLAP::MultiArg< T > Class Template Reference
An argument that allows multiple values of type T to be specified.
#include <MultiArg.h>
Public Types
typedef std::vector< T > container_type
typedef container_type::iterator iterator
typedef container_type::const_iterator const_iterator
Public Member Functions
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const std::string &typeDesc, ArgContainer &parser, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, Visitor *v=NULL)
Constructor.
MultiArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, const Constraint< T > *constraint, ArgContainer &parser, Visitor *v=NULL)
Constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
const std::vector< T > & getValue () const
Returns a vector of type T containing the values parsed from the command line.
const_iterator begin () const
Returns an iterator over the values parsed from the command line.
const_iterator end () const
Returns the end of the values parsed from the command line.
virtual std::string shortID (const std::string &val="val") const
Returns the a short id string.
virtual std::string longID (const std::string &val="val") const
Returns the a long id string.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
virtual bool hasLabel () const
Protected Member Functions
void _extractValue (const std::string &val)
Extracts the value from the string.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes
std::vector< T > _values
The list of values parsed from the CmdLine.
std::string _typeDesc
The description of type T to be used in the usage.
const Constraint< T > * _constraint
A constraint that the values of this Arg must conform to.
bool _allowMore
Used by MultiArg to decide whether to keep parsing for this arg.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Detailed Description
template<class T>
class TCLAP::MultiArg< T >
An argument that allows multiple values of type T to be specified.
Very similar to a ValueArg, except a vector of values will be returned instead of just one.
Definition at line 41 of file MultiArg.h.
Member Typedef Documentation
const_iterator
template<class T> typedef container_type::const_iterator TCLAP::MultiArg< T >::const_iterator
Definition at line 45 of file MultiArg.h.
container_type
template<class T> typedef std::vector<T> TCLAP::MultiArg< T >::container_type
Definition at line 43 of file MultiArg.h.
iterator
template<class T> typedef container_type::iterator TCLAP::MultiArg< T >::iterator
Definition at line 44 of file MultiArg.h.
Constructor & Destructor Documentation
MultiArg() [1/4]
template<class T> TCLAP::MultiArg< T >::MultiArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, Visitor * v = NULL)
Constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 213 of file MultiArg.h.
References TCLAP::Arg::_acceptsMultipleValues, _allowMore, _constraint, _typeDesc, and _values.
Referenced by TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), and TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg().
MultiArg() [2/4]
template<class T> TCLAP::MultiArg< T >::MultiArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, const std::string & typeDesc, ArgContainer & parser, Visitor * v = NULL)
Constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 225 of file MultiArg.h.
References TCLAP::Arg::_acceptsMultipleValues, _allowMore, _constraint, _typeDesc, _values, and TCLAP::ArgContainer::add().
MultiArg() [3/4]
template<class T> TCLAP::MultiArg< T >::MultiArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, const Constraint< T > * constraint, Visitor * v = NULL)
Constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 242 of file MultiArg.h.
References TCLAP::Arg::_acceptsMultipleValues, _allowMore, _constraint, _typeDesc, _values, and shortID().
MultiArg() [4/4]
template<class T> TCLAP::MultiArg< T >::MultiArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, const Constraint< T > * constraint, ArgContainer & parser, Visitor * v = NULL)
Constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 254 of file MultiArg.h.
References TCLAP::Arg::_acceptsMultipleValues, _allowMore, _constraint, _typeDesc, _values, TCLAP::ArgContainer::add(), and shortID().
Member Function Documentation
_extractValue()
template<class T> void TCLAP::MultiArg< T >::_extractValue (const std::string & val) protected
Extracts the value from the string.
Attempts to parse string as type T, if this fails an exception is thrown.
Parameters
val - The string to be read.
Definition at line 322 of file MultiArg.h.
References _constraint, _values, TCLAP::ArgException::error(), TCLAP::ExtractValue(), and TCLAP::Arg::toString().
Referenced by processArg(), and TCLAP::UnlabeledMultiArg< T >::processArg().
allowMore()
template<class T> bool TCLAP::MultiArg< T >::allowMore () virtual
Used for MultiArgs to determine whether args can still be set.
Reimplemented from TCLAP::Arg.
Definition at line 340 of file MultiArg.h.
References _allowMore.
begin()
template<class T> const_iterator TCLAP::MultiArg< T >::begin () const inline
Returns an iterator over the values parsed from the command line.
Definition at line 180 of file MultiArg.h.
References _values.
end()
template<class T> const_iterator TCLAP::MultiArg< T >::end () const inline
Returns the end of the values parsed from the command line.
Definition at line 186 of file MultiArg.h.
References _values.
getValue()
template<class T> const std::vector< T > & TCLAP::MultiArg< T >::getValue () const inline
Returns a vector of type T containing the values parsed from the command line.
Definition at line 174 of file MultiArg.h.
References _values.
longID()
template<class T> std::string TCLAP::MultiArg< T >::longID (const std::string & val = "val") const virtual
Returns the a long id string.
Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledMultiArg< T >.
Definition at line 316 of file MultiArg.h.
References _typeDesc, and TCLAP::Arg::longID().
processArg()
template<class T> bool TCLAP::MultiArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument.
This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed from main().
Implements TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledMultiArg< T >.
Definition at line 268 of file MultiArg.h.
References TCLAP::Arg::_alreadySet, TCLAP::Arg::_checkWithVisitor(), _extractValue(), TCLAP::Arg::_hasBlanks(), TCLAP::Arg::_setBy, TCLAP::Arg::argMatches(), TCLAP::Arg::delimiter(), TCLAP::Arg::toString(), and TCLAP::Arg::trimFlag().
reset()
template<class T> void TCLAP::MultiArg< T >::reset () virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented from TCLAP::Arg.
Definition at line 347 of file MultiArg.h.
References _values, and TCLAP::Arg::reset().
shortID()
template<class T> std::string TCLAP::MultiArg< T >::shortID (const std::string & val = "val") const virtual
Returns the a short id string.
Used in the usage.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledMultiArg< T >.
Definition at line 307 of file MultiArg.h.
References _typeDesc, and TCLAP::Arg::shortID().
Referenced by MultiArg(), and MultiArg().
Member Data Documentation
_allowMore
template<class T> bool TCLAP::MultiArg< T >::_allowMore protected
Used by MultiArg to decide whether to keep parsing for this arg.
Definition at line 75 of file MultiArg.h.
Referenced by allowMore(), MultiArg(), MultiArg(), MultiArg(), and MultiArg().
_constraint
template<class T> const Constraint<T>* TCLAP::MultiArg< T >::_constraint protected
A constraint that the values of this Arg must conform to.
Definition at line 61 of file MultiArg.h.
Referenced by _extractValue(), MultiArg(), MultiArg(), MultiArg(), and MultiArg().
_typeDesc
template<class T> std::string TCLAP::MultiArg< T >::_typeDesc protected
The description of type T to be used in the usage.
Definition at line 56 of file MultiArg.h.
Referenced by longID(), TCLAP::UnlabeledMultiArg< T >::longID(), MultiArg(), MultiArg(), MultiArg(), MultiArg(), and shortID().
_values
template<class T> std::vector<T> TCLAP::MultiArg< T >::_values protected
The list of values parsed from the CmdLine.
Definition at line 51 of file MultiArg.h.
Referenced by _extractValue(), begin(), end(), getValue(), MultiArg(), MultiArg(), MultiArg(), MultiArg(), and reset().
The documentation for this class was generated from the following file:
MultiArg.h