tclap: TCLAP::ArgGroup Class Reference
TCLAP::ArgGroup Class Reference abstract
ArgGroup is the base class for implementing groups of arguments that are mutually exclusive (it replaces the deprecated xor handler).
#include <ArgGroup.h>
Public Types
typedef std::list< Arg * > Container
typedef Container::iterator iterator
typedef Container::const_iterator const_iterator
Public Member Functions
virtual ~ArgGroup ()
virtual ArgContainer & add (Arg &arg)
Add an argument to this arg group.
virtual ArgContainer & add (Arg *arg)
Add an argument to this arg group.
virtual bool validate ()=0
Validates that the constraints of the ArgGroup are satisfied.
virtual bool isRequired () const =0
Returns true if this argument group is required.
virtual bool isExclusive () const =0
Returns true if this argument group is exclusive.
void setParser (CmdLineInterface &parser)
Used by the parser to connect itself to this arg group.
virtual bool showAsGroup () const
If arguments in this group should show up as grouped in help.
const std::string getName () const
Returns the argument group's name.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Public Member Functions inherited from TCLAP::ArgContainer
virtual ~ArgContainer ()
Protected Member Functions
ArgGroup ()
Protected Attributes
CmdLineInterface * _parser
Container _args
Detailed Description
ArgGroup is the base class for implementing groups of arguments that are mutually exclusive (it replaces the deprecated xor handler).
It is not expected to be used directly, rather one of the EitherOf or OneOf derived classes are used.
Definition at line 41 of file ArgGroup.h.
Member Typedef Documentation
const_iterator
typedef Container::const_iterator TCLAP::ArgGroup::const_iterator
Definition at line 45 of file ArgGroup.h.
Container
typedef std::list<Arg *> TCLAP::ArgGroup::Container
Definition at line 43 of file ArgGroup.h.
iterator
typedef Container::iterator TCLAP::ArgGroup::iterator
Definition at line 44 of file ArgGroup.h.
Constructor & Destructor Documentation
~ArgGroup()
virtual TCLAP::ArgGroup::~ArgGroup () inline virtual
Definition at line 47 of file ArgGroup.h.
ArgGroup()
TCLAP::ArgGroup::ArgGroup () inline protected
Definition at line 116 of file ArgGroup.h.
References _args, and _parser.
Member Function Documentation
add() [1/2]
virtual ArgContainer & TCLAP::ArgGroup::add (Arg & arg) inline virtual
Add an argument to this arg group.
Implements TCLAP::ArgContainer.
Reimplemented in TCLAP::ExclusiveArgGroup.
Definition at line 50 of file ArgGroup.h.
References add().
Referenced by add(), and TCLAP::ExclusiveArgGroup::add().
add() [2/2]
ArgContainer & TCLAP::ArgGroup::add (Arg * arg) inline virtual
Add an argument to this arg group.
Implements TCLAP::ArgContainer.
Reimplemented in TCLAP::ExclusiveArgGroup, and TCLAP::StandaloneArgs.
Definition at line 192 of file ArgGroup.h.
References _args, _parser, begin(), end(), and TCLAP::Arg::longID().
begin() [1/2]
iterator TCLAP::ArgGroup::begin () inline
Definition at line 109 of file ArgGroup.h.
References _args.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), add(), TCLAP::StandaloneArgs::add(), TCLAP::CountVisibleArgs(), getName(), TCLAP::DocBookOutput::printLongArg(), setParser(), and TCLAP::ExclusiveArgGroup::validate().
begin() [2/2]
const_iterator TCLAP::ArgGroup::begin () const inline
Definition at line 111 of file ArgGroup.h.
References _args.
end() [1/2]
iterator TCLAP::ArgGroup::end () inline
Definition at line 110 of file ArgGroup.h.
References _args.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), add(), TCLAP::StandaloneArgs::add(), TCLAP::CountVisibleArgs(), getName(), TCLAP::DocBookOutput::printLongArg(), setParser(), and TCLAP::ExclusiveArgGroup::validate().
end() [2/2]
const_iterator TCLAP::ArgGroup::end () const inline
Definition at line 112 of file ArgGroup.h.
References _args.
getName()
const std::string TCLAP::ArgGroup::getName () const inline
Returns the argument group's name.
Definition at line 230 of file ArgGroup.h.
References begin(), and end().
isExclusive()
virtual bool TCLAP::ArgGroup::isExclusive () const pure virtual
Returns true if this argument group is exclusive.
Implemented in TCLAP::AnyOf, and TCLAP::ExclusiveArgGroup.
Referenced by TCLAP::StdOutput::_longUsage().
isRequired()
virtual bool TCLAP::ArgGroup::isRequired () const pure virtual
Returns true if this argument group is required.
Implemented in TCLAP::AnyOf, TCLAP::EitherOf, and TCLAP::OneOf.
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), TCLAP::internal::GroupChoice(), TCLAP::DocBookOutput::printLongArg(), and TCLAP::ExclusiveArgGroup::validate().
setParser()
void TCLAP::ArgGroup::setParser (CmdLineInterface & parser) inline
Used by the parser to connect itself to this arg group.
Definition at line 90 of file ArgGroup.h.
References _parser, TCLAP::CmdLineInterface::addToArgList(), begin(), and end().
Referenced by TCLAP::CmdLine::add().
showAsGroup()
virtual bool TCLAP::ArgGroup::showAsGroup () const inline virtual
If arguments in this group should show up as grouped in help.
Reimplemented in TCLAP::StandaloneArgs.
Definition at line 104 of file ArgGroup.h.
Referenced by TCLAP::internal::GroupChoice().
validate()
virtual bool TCLAP::ArgGroup::validate () pure virtual
Validates that the constraints of the ArgGroup are satisfied.
Implemented in TCLAP::AnyOf, and TCLAP::ExclusiveArgGroup.
Member Data Documentation
_args
Container TCLAP::ArgGroup::_args protected
Definition at line 124 of file ArgGroup.h.
Referenced by add(), TCLAP::StandaloneArgs::add(), ArgGroup(), begin(), begin(), end(), and end().
_parser
CmdLineInterface* TCLAP::ArgGroup::_parser protected
Definition at line 123 of file ArgGroup.h.
Referenced by add(), ArgGroup(), and setParser().
The documentation for this class was generated from the following file:
ArgGroup.h