tclap: TCLAP::MultiSwitchArg Class Reference
TCLAP::MultiSwitchArg Class Reference
A multiple switch argument.
#include <MultiSwitchArg.h>
Public Member Functions
MultiSwitchArg (const std::string &flag, const std::string &name, const std::string &desc, int init=0, Visitor *v=NULL)
MultiSwitchArg constructor.
MultiSwitchArg (const std::string &flag, const std::string &name, const std::string &desc, ArgContainer &parser, int init=0, Visitor *v=NULL)
MultiSwitchArg constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
int getValue () const
Returns int, the number of times the switch has been set.
std::string shortID (const std::string &val) const
Returns the shortID for this Arg.
std::string longID (const std::string &val) const
Returns the longID for this Arg.
void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::SwitchArg
SwitchArg (const std::string &flag, const std::string &name, const std::string &desc, bool def=false, Visitor *v=NULL)
SwitchArg constructor.
SwitchArg (const std::string &flag, const std::string &name, const std::string &desc, ArgContainer &parser, bool def=false, Visitor *v=NULL)
SwitchArg constructor.
bool combinedSwitchesMatch (std::string &combined)
Checks a string to see if any of the chars in the string match the flag for this Switch.
bool getValue () const
Returns bool, whether or not the switch has been set.
operator bool () const
A SwitchArg can be used as a boolean, indicating whether or not the switch has been set.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
std::string getDescription (bool required) const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
const std::string & setBy () const
Returns the value specified to set this flag (like -a or –all).
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
virtual bool allowMore ()
Used for MultiArgs to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
virtual void hideFromHelp (bool hide=true)
Hide this argument from the help output (e.g., when specifying the –help flag or on error.
virtual bool visibleInHelp () const
Returns true if this Arg is visible in the help output.
virtual bool hasLabel () const
Protected Attributes
int _value
The value of the switch.
int _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Protected Attributes inherited from TCLAP::SwitchArg
bool _value
The value of the switch.
bool _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single word namd identifying the argument.
std::string _description
Description of the argument.
const bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
std::string _setBy
Indicates the value specified to set this flag (like -a or –all).
Visitor * _visitor
A pointer to a visitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _acceptsMultipleValues
bool _visibleInHelp
Indicates if the argument is visible in the help output (e.g., when specifying –help).
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Visitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Detailed Description
A multiple switch argument.
If the switch is set on the command line, then the getValue method will return the number of times the switch appears.
Definition at line 40 of file MultiSwitchArg.h.
Constructor & Destructor Documentation
MultiSwitchArg() [1/2]
TCLAP::MultiSwitchArg::MultiSwitchArg (const std::string & flag, const std::string & name, const std::string & desc, int init = 0, Visitor * v = NULL) inline
MultiSwitchArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
init - Optional. The initial/default value of this Arg. Defaults to 0.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 116 of file MultiSwitchArg.h.
References _default, _value, and TCLAP::SwitchArg::SwitchArg().
MultiSwitchArg() [2/2]
TCLAP::MultiSwitchArg::MultiSwitchArg (const std::string & flag, const std::string & name, const std::string & desc, ArgContainer & parser, int init = 0, Visitor * v = NULL) inline
MultiSwitchArg constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
parser - A CmdLine parser object to add this Arg to
init - Optional. The initial/default value of this Arg. Defaults to 0.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 122 of file MultiSwitchArg.h.
References _default, _value, TCLAP::ArgContainer::add(), and TCLAP::SwitchArg::SwitchArg().
Member Function Documentation
getValue()
int TCLAP::MultiSwitchArg::getValue () const inline
Returns int, the number of times the switch has been set.
Definition at line 101 of file MultiSwitchArg.h.
References _value.
longID()
std::string TCLAP::MultiSwitchArg::longID (const std::string & val) const inline virtual
Returns the longID for this Arg.
Reimplemented from TCLAP::Arg.
Definition at line 165 of file MultiSwitchArg.h.
References TCLAP::Arg::longID().
processArg()
bool TCLAP::MultiSwitchArg::processArg (int * i, std::vector< std::string > & args) inline virtual
Handles the processing of the argument.
This re-implements the SwitchArg version of this method to set the _value of the argument appropriately.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed in from main().
Reimplemented from TCLAP::SwitchArg.
Definition at line 131 of file MultiSwitchArg.h.
References TCLAP::Arg::_alreadySet, TCLAP::Arg::_checkWithVisitor(), TCLAP::Arg::_setBy, _value, TCLAP::Arg::argMatches(), and TCLAP::SwitchArg::combinedSwitchesMatch().
reset()
void TCLAP::MultiSwitchArg::reset () inline virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented from TCLAP::SwitchArg.
Definition at line 169 of file MultiSwitchArg.h.
References _default, and _value.
shortID()
std::string TCLAP::MultiSwitchArg::shortID (const std::string & val) const inline virtual
Returns the shortID for this Arg.
Reimplemented from TCLAP::Arg.
Definition at line 161 of file MultiSwitchArg.h.
References TCLAP::Arg::shortID().
Member Data Documentation
_default
int TCLAP::MultiSwitchArg::_default protected
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Definition at line 51 of file MultiSwitchArg.h.
Referenced by MultiSwitchArg(), MultiSwitchArg(), and reset().
_value
int TCLAP::MultiSwitchArg::_value protected
The value of the switch.
Definition at line 45 of file MultiSwitchArg.h.
Referenced by getValue(), MultiSwitchArg(), MultiSwitchArg(), processArg(), and reset().
The documentation for this class was generated from the following file:
MultiSwitchArg.h