tclap: TCLAP::internal Namespace Reference
TCLAP::internal Namespace Reference
Functions
const char * GroupChoice (const ArgGroup &group)
bool IsVisibleShortSwitch (const Arg &arg)
bool IsVisibleLongSwitch (const Arg &arg)
bool IsVisibleOption (const Arg &arg)
bool CompareShortID (const Arg *a, const Arg *b)
bool CompareOptions (std::pair< const Arg *, bool > a, std::pair< const Arg *, bool > b)
Function Documentation
CompareOptions()
bool TCLAP::internal::CompareOptions (std::pair< const Arg *, bool > a, std::pair< const Arg *, bool > b) inline
Definition at line 196 of file StdOutput.h.
References CompareShortID().
Referenced by TCLAP::StdOutput::_shortUsage().
CompareShortID()
bool TCLAP::internal::CompareShortID (const Arg * a, const Arg * b) inline
Definition at line 184 of file StdOutput.h.
References TCLAP::Arg::getFlag(), and TCLAP::Arg::shortID().
Referenced by TCLAP::StdOutput::_shortUsage(), and CompareOptions().
GroupChoice()
const char * TCLAP::internal::GroupChoice (const ArgGroup & group)
Definition at line 91 of file DocBookOutput.h.
References TCLAP::ArgGroup::isRequired(), and TCLAP::ArgGroup::showAsGroup().
Referenced by TCLAP::DocBookOutput::usage().
IsVisibleLongSwitch()
bool TCLAP::internal::IsVisibleLongSwitch (const Arg & arg) inline
Definition at line 173 of file StdOutput.h.
References TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::Arg::ignoreNameString(), TCLAP::Arg::isValueRequired(), and TCLAP::Arg::visibleInHelp().
Referenced by TCLAP::StdOutput::_shortUsage().
IsVisibleOption()
bool TCLAP::internal::IsVisibleOption (const Arg & arg) inline
Definition at line 179 of file StdOutput.h.
References TCLAP::Arg::getName(), TCLAP::Arg::hasLabel(), TCLAP::Arg::ignoreNameString(), TCLAP::Arg::isValueRequired(), and TCLAP::Arg::visibleInHelp().
Referenced by TCLAP::StdOutput::_shortUsage().
IsVisibleShortSwitch()
bool TCLAP::internal::IsVisibleShortSwitch (const Arg & arg) inline
Definition at line 167 of file StdOutput.h.
References TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::Arg::ignoreNameString(), TCLAP::Arg::isValueRequired(), and TCLAP::Arg::visibleInHelp().
Referenced by TCLAP::StdOutput::_shortUsage().