tclap: TCLAP Namespace Reference
TCLAP Namespace Reference
Namespaces
namespace internal
Classes
class AnyOf
Implements a group of arguments where any combination is possible (including all or none).
class Arg
A virtual base class that defines the essential data for all arguments.
class ArgContainer
Interface that allows adding an Arg to a "container".
class ArgException
A simple class that defines and argument exception.
class ArgGroup
ArgGroup is the base class for implementing groups of arguments that are mutually exclusive (it replaces the deprecated xor handler).
class ArgParseException
Thrown from within the child Arg classes when it fails to properly parse the argument it has been passed.
class ArgTraits
Arg traits are used to get compile type specialization when parsing argument values.
struct ArgTraits< std::string >
class CmdLine
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
class CmdLineInterface
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
class CmdLineOutput
The interface that any output object must implement.
class CmdLineParseException
Thrown from CmdLine when the arguments on the command line are not properly specified, e.g.
class Constraint
The interface that defines the interaction between the Arg and Constraint.
class DeferDelete
DeferDelete can be used by objects that need to allocate arbitrary other objects to live for the duration of the first object.
class DocBookOutput
A class that generates DocBook output for usage() method for the given CmdLine and its Args.
class EitherOf
Implements a group of arguments where at most one can be selected.
class ExclusiveArgGroup
Implements common functionality for exclusive argument groups.
class ExitException
Thrown when TCLAP thinks the program should exit.
class HelpVisitor
A Visitor object that calls the usage method of the given CmdLineOutput object for the specified CmdLine object.
class IgnoreRestVisitor
A Visitor that tells the CmdLine to begin ignoring arguments after this one is parsed.
class MultiArg
An argument that allows multiple values of type T to be specified.
class MultiSwitchArg
A multiple switch argument.
class OneOf
Implements a group of arguments where exactly one must be selected.
class OptionalUnlabeledTracker
class SpecificationException
Thrown from Arg and CmdLine when an Arg is improperly specified, e.g.
class StandaloneArgs
class StdOutput
A class that isolates any output from the CmdLine object so that it may be easily modified.
struct StringLike
A string like argument value type is a value that can be set using operator=(string).
struct StringLikeTrait
A class can inherit from this object to make it have string like traits.
class SwitchArg
A simple switch argument.
class UnlabeledMultiArg
Just like a MultiArg, except that the arguments are unlabeled.
class UnlabeledValueArg
The basic unlabeled argument that parses a value.
class ValueArg
The basic labeled argument that parses a value.
struct ValueLike
A value like argument value type is a value that can be set using operator>>.
struct ValueLikeTrait
A class can inherit from this object to make it have value like traits.
class ValuesConstraint
A Constraint that constrains the Arg to only those values specified in the constraint.
class VersionVisitor
A Visitor that will call the version method of the given CmdLineOutput for the specified CmdLine object and then exit.
class Visitor
A base class that defines the interface for visitors.
Typedefs
typedef std::list< Arg * >::const_iterator ArgListIterator
Typedef of an Arg list iterator.
typedef std::vector< Arg * >::const_iterator ArgVectorIterator
Typedef of an Arg vector iterator.
typedef std::list< Visitor * >::const_iterator VisitorListIterator
Typedef of a Visitor list iterator.
typedef std::istringstream istringstream
typedef std::ostringstream ostringstream
Functions
template<typename T>
void ExtractValue (T &destVal, const std::string &strVal, ValueLike vl)
template<typename T>
void ExtractValue (T &destVal, const std::string &strVal, StringLike sl)
int CountVisibleArgs (const ArgGroup &g)
bool isInArgGroup (const Arg *arg, const std::list< ArgGroup * > &argSets)
void removeArgsInArgGroups (std::list< Arg * > &argList, const std::list< ArgGroup * > &argSets)
std::string removeSuffix (std::string s, const std::string &suffix)
std::string basename (std::string s)
template<typename T>
void SetString (T &dst, const std::string &src)
void removeChar (std::string &s, char r)
bool cmpSwitch (const char &a, const char &b)
Variables
const char PATH_SEPARATOR
Typedef Documentation
ArgListIterator
typedef std::list<Arg*>::const_iterator TCLAP::ArgListIterator
Typedef of an Arg list iterator.
Definition at line 380 of file Arg.h.
ArgVectorIterator
typedef std::vector<Arg*>::const_iterator TCLAP::ArgVectorIterator
Typedef of an Arg vector iterator.
Definition at line 385 of file Arg.h.
istringstream
typedef std::istringstream TCLAP::istringstream
Definition at line 37 of file sstream.h.
ostringstream
typedef std::ostringstream TCLAP::ostringstream
Definition at line 38 of file sstream.h.
VisitorListIterator
typedef std::list<Visitor*>::const_iterator TCLAP::VisitorListIterator
Typedef of a Visitor list iterator.
Definition at line 390 of file Arg.h.
Function Documentation
basename()
std::string TCLAP::basename (std::string s) inline
Definition at line 110 of file CmdLineOutput.h.
References PATH_SEPARATOR, and removeSuffix().
Referenced by TCLAP::CmdLine::parse().
cmpSwitch()
bool TCLAP::cmpSwitch (const char & a, const char & b) inline
Definition at line 155 of file StdOutput.h.
Referenced by TCLAP::StdOutput::_shortUsage().
CountVisibleArgs()
int TCLAP::CountVisibleArgs (const ArgGroup & g) inline
Definition at line 243 of file ArgGroup.h.
References TCLAP::ArgGroup::begin(), and TCLAP::ArgGroup::end().
Referenced by TCLAP::StdOutput::_longUsage(), TCLAP::StdOutput::_shortUsage(), TCLAP::DocBookOutput::printLongArg(), and TCLAP::DocBookOutput::usage().
ExtractValue() [1/2]
template<typename T> void TCLAP::ExtractValue (T & destVal, const std::string & strVal, StringLike sl)
Definition at line 437 of file Arg.h.
References SetString().
ExtractValue() [2/2]
template<typename T> void TCLAP::ExtractValue (T & destVal, const std::string & strVal, ValueLike vl)
Definition at line 399 of file Arg.h.
Referenced by TCLAP::MultiArg< T >::_extractValue(), and TCLAP::ValueArg< T >::_extractValue().
isInArgGroup()
bool TCLAP::isInArgGroup (const Arg * arg, const std::list< ArgGroup * > & argSets) inline
Definition at line 79 of file CmdLineOutput.h.
Referenced by removeArgsInArgGroups().
removeArgsInArgGroups()
void TCLAP::removeArgsInArgGroups (std::list< Arg * > & argList, const std::list< ArgGroup * > & argSets) inline
Definition at line 89 of file CmdLineOutput.h.
References isInArgGroup().
removeChar()
void TCLAP::removeChar (std::string & s, char r) inline
Definition at line 148 of file StdOutput.h.
removeSuffix()
std::string TCLAP::removeSuffix (std::string s, const std::string & suffix) inline
Definition at line 101 of file CmdLineOutput.h.
Referenced by basename().
SetString()
template<typename T> void TCLAP::SetString (T & dst, const std::string & src)
Definition at line 55 of file StandardTraits.h.
Referenced by ExtractValue().
Variable Documentation
PATH_SEPARATOR
const char TCLAP::PATH_SEPARATOR
Initial value:
=
    '/'
Definition at line 39 of file CmdLineOutput.h.
Referenced by basename().